sonar.projectKey=vivouch
sonar.projectName=ViVouch
sonar.sourceEncoding=UTF-8
sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,backend/tests-node,frontend/tests-node
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,backend/prisma/migrations/**,frontend/src/pages/test/**,frontend/src/**/*.test.js
sonar.coverage.exclusions=frontend/src/pages/test/**,frontend/src/**/*.test.js
sonar.javascript.node.maxspace=4096
