import { useCallback, useEffect, useState } from 'react';
import { listAdminTickets, respondTicket } from '../../features/marketplace/api/marketplace.api';

export default function SupportTicketsPage() {
  const [items, setItems] = useState([]); const [status, setStatus] = useState(''); const [state, setState] = useState({ loading: true, error: '', success: '' });
  const load = useCallback(async () => { try { const data = await listAdminTickets({ status: status || undefined }); setItems(data.items || []); setState((c) => ({ ...c, loading: false, error: '' })); } catch (error) { setState((c) => ({ ...c, loading: false, error: error?.response?.data?.message || 'Không thể tải ticket.' })); } }, [status]);
  useEffect(() => { setState((c) => ({ ...c, loading: true })); load(); }, [load]);
  async function respond(item) { const adminResponse = window.prompt('Nội dung phản hồi:'); if (!adminResponse) return; const nextStatus = window.confirm('Đóng yêu cầu sau khi phản hồi?') ? 'RESOLVED' : 'PROCESSING'; try { await respondTicket(item.id, { status: nextStatus, adminResponse }); setState((c) => ({ ...c, success: 'Đã gửi phản hồi.', error: '' })); await load(); } catch (error) { setState((c) => ({ ...c, error: error?.response?.data?.message || 'Không thể phản hồi.', success: '' })); } }
  return <div className="p-6 space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Hỗ trợ & khiếu nại</h1><p className="text-sm text-gray-500">Quy trình một cấp giữa Customer và Admin.</p></div><select className="select select-bordered" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Tất cả</option><option value="OPEN">Mới</option><option value="PROCESSING">Đang xử lý</option><option value="RESOLVED">Đã xử lý</option><option value="REJECTED">Từ chối</option></select></div>{state.error && <div className="alert alert-error">{state.error}</div>}{state.success && <div className="alert alert-success">{state.success}</div>}{state.loading ? <div className="py-12 text-center"><span className="loading loading-spinner loading-lg" /></div> : <div className="grid gap-3">{items.map((item) => <article className="card bg-white border border-gray-200" key={item.id}><div className="card-body py-4"><div className="flex flex-wrap justify-between gap-3"><div><b>{item.subject}</b><div className="text-sm text-gray-500">{item.user?.fullName} — {item.user?.email}</div></div><span className="badge badge-outline">{item.status}</span></div><p className="text-sm">{item.description}</p>{item.adminResponse && <div className="alert"><span>{item.adminResponse}</span></div>}<div className="card-actions justify-end"><button className="btn btn-primary btn-sm" onClick={() => respond(item)}>Phản hồi</button></div></div></article>)}{items.length === 0 && <p className="py-10 text-center text-gray-500">Không có ticket.</p>}</div>}</div>;
}
