export const AUDIT_ACTIONS = {
  ADMIN_APPROVE_PARTNER: "ADMIN_APPROVE_PARTNER",
  ADMIN_REJECT_PARTNER: "ADMIN_REJECT_PARTNER",
  PARTNER_CREATE_VOUCHER: "PARTNER_CREATE_VOUCHER",
  PARTNER_SUBMIT_VOUCHER: "PARTNER_SUBMIT_VOUCHER",
  ADMIN_APPROVE_VOUCHER: "ADMIN_APPROVE_VOUCHER",
  ADMIN_REJECT_VOUCHER: "ADMIN_REJECT_VOUCHER",
  CUSTOMER_CHECKOUT: "CUSTOMER_CHECKOUT",
  SYSTEM_ISSUE_VOUCHER_CODE: "SYSTEM_ISSUE_VOUCHER_CODE",
  PARTNER_REDEEM_VOUCHER: "PARTNER_REDEEM_VOUCHER",
  ADMIN_LOCK_USER: "ADMIN_LOCK_USER",
  ADMIN_UNLOCK_USER: "ADMIN_UNLOCK_USER",
  CUSTOMER_UPDATE_PROFILE: "CUSTOMER_UPDATE_PROFILE",
  CUSTOMER_CHANGE_PASSWORD: "CUSTOMER_CHANGE_PASSWORD" // NOSONAR
};
