export const AUDIT_ACTIONS = {
  ADMIN_APPROVE_PARTNER: "ADMIN_APPROVE_PARTNER",
  ADMIN_REJECT_PARTNER: "ADMIN_REJECT_PARTNER",
  // Preserve the established persisted action names used by the canonical
  // audit contract and historical data.
  PARTNER_CREATE_VOUCHER: "CREATE_VOUCHER",
  PARTNER_SUBMIT_VOUCHER: "SUBMIT_VOUCHER",
  ADMIN_APPROVE_VOUCHER: "ADMIN_APPROVE_VOUCHER",
  ADMIN_REJECT_VOUCHER: "ADMIN_REJECT_VOUCHER",
  CUSTOMER_CHECKOUT: "CUSTOMER_CHECKOUT",
  CUSTOMER_CREATE_REVIEW: "CUSTOMER_CREATE_REVIEW",
  SYSTEM_ISSUE_VOUCHER_CODE: "SYSTEM_ISSUE_VOUCHER_CODE",
  PARTNER_REDEEM_VOUCHER: "PARTNER_REDEEM_VOUCHER",
  ADMIN_LOCK_USER: "ADMIN_LOCK_USER",
  ADMIN_UNLOCK_USER: "ADMIN_UNLOCK_USER",
  ADMIN_ASSIGN_ROLE: "ADMIN_ASSIGN_ROLE",
  ADMIN_SUSPEND_PARTNER: "ADMIN_SUSPEND_PARTNER",
  ADMIN_REACTIVATE_PARTNER: "ADMIN_REACTIVATE_PARTNER",
  ADMIN_CANCEL_ORDER: "ADMIN_CANCEL_ORDER",
  ADMIN_MANAGE_CONTENT: "ADMIN_MANAGE_CONTENT",
  CUSTOMER_UPDATE_PROFILE: "CUSTOMER_UPDATE_PROFILE",
  CUSTOMER_CHANGE_PASSWORD: "CUSTOMER_CHANGE_PASSWORD" // NOSONAR
};
