export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  VOUCHER_NOT_FOUND: "VOUCHER_NOT_FOUND",
  VOUCHER_NOT_ON_SALE: "VOUCHER_NOT_ON_SALE",
  VOUCHER_OUT_OF_STOCK: "VOUCHER_OUT_OF_STOCK",
  VOUCHER_EXPIRED: "VOUCHER_EXPIRED",
  VOUCHER_ALREADY_USED: "VOUCHER_ALREADY_USED",
  INVALID_PARTNER_SCOPE: "INVALID_PARTNER_SCOPE",
  RATE_LIMITED: "RATE_LIMITED"
};
