export const VOUCHER_STATUS = {
  DRAFT: "DRAFT",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  ON_SALE: "ON_SALE",
  PAUSED: "PAUSED",
  EXPIRED: "EXPIRED",
  REJECTED: "REJECTED",
  SUSPENDED: "SUSPENDED"
};

export const VOUCHER_CODE_STATUS = {
  ISSUED: "ISSUED",
  USED: "USED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
  LOCKED: "LOCKED",
  REFUND_PENDING: "REFUND_PENDING",
  REFUNDED: "REFUNDED"
};

export const voucherTransitions = {
  [VOUCHER_STATUS.DRAFT]: [VOUCHER_STATUS.PENDING_APPROVAL],
  [VOUCHER_STATUS.REJECTED]: [VOUCHER_STATUS.PENDING_APPROVAL],
  [VOUCHER_STATUS.PENDING_APPROVAL]: [VOUCHER_STATUS.APPROVED, VOUCHER_STATUS.REJECTED],
  [VOUCHER_STATUS.APPROVED]: [VOUCHER_STATUS.ON_SALE],
  [VOUCHER_STATUS.ON_SALE]: [VOUCHER_STATUS.PAUSED, VOUCHER_STATUS.EXPIRED, VOUCHER_STATUS.SUSPENDED],
  [VOUCHER_STATUS.PAUSED]: [VOUCHER_STATUS.ON_SALE],
};
