import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { requestPasswordReset, resetPassword } from '../../features/auth/api/auth.api';

export function ForgotPasswordPage() {
  const navigate = useNavigate();
  const [step, setStep] = useState('REQUEST'); const [email, setEmail] = useState(''); const [otp, setOtp] = useState(''); const [password, setPassword] = useState('');
  const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function request(e) { e.preventDefault(); setLoading(true); setError(''); try { const r=await requestPasswordReset(email); setMessage(r.message); setStep('RESET'); } catch(err){setError(err?.response?.data?.message||'Không thể gửi OTP.');} finally{setLoading(false);} }
  async function reset(e) { e.preventDefault(); setLoading(true); setError(''); try { await resetPassword(email,otp,password); navigate('/login',{state:{message:'Đặt lại mật khẩu thành công.'}}); } catch(err){setError(err?.response?.data?.message||'Không thể đặt lại mật khẩu.');} finally{setLoading(false);} }
  return <main className="min-h-screen bg-base-200 grid place-items-center p-4"><div className="card bg-base-100 shadow-xl w-full max-w-md"><div className="card-body"><h1 className="card-title text-2xl">Quên mật khẩu</h1><p className="text-sm text-base-content/60">OTP sẽ được gửi qua SMTP tới email đăng ký.</p>{message&&<div className="alert alert-success text-sm">{message}</div>}{error&&<div className="alert alert-error text-sm">{error}</div>}{step==='REQUEST'?<form onSubmit={request} className="space-y-4"><input type="email" className="input input-bordered w-full" value={email} onChange={(e)=>setEmail(e.target.value)} required/><button className="btn btn-primary w-full" disabled={loading}>Gửi OTP</button></form>:<form onSubmit={reset} className="space-y-4"><input className="input input-bordered w-full" value={otp} onChange={(e)=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="OTP 6 số" pattern="[0-9]{6}" required/><input type="password" className="input input-bordered w-full" value={password} onChange={(e)=>setPassword(e.target.value)} placeholder="Mật khẩu mới" minLength="8" required/><button className="btn btn-primary w-full" disabled={loading}>Đặt lại mật khẩu</button></form>}<Link to="/login" className="btn btn-ghost btn-sm">Quay lại đăng nhập</Link></div></div></main>;
}
